# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ext-szombatb/Projects/ClashC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ext-szombatb/Projects/ClashC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ext-szombatb/Projects/ClashC/CMakeFiles /home/ext-szombatb/Projects/ClashC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ext-szombatb/Projects/ClashC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClashC

# Build rule for target.
ClashC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClashC
.PHONY : ClashC

# fast build rule for target.
ClashC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/build
.PHONY : ClashC/fast

exec/exec_engine.o: exec/exec_engine.c.o
.PHONY : exec/exec_engine.o

# target to build an object file
exec/exec_engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/exec_engine.c.o
.PHONY : exec/exec_engine.c.o

exec/exec_engine.i: exec/exec_engine.c.i
.PHONY : exec/exec_engine.i

# target to preprocess a source file
exec/exec_engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/exec_engine.c.i
.PHONY : exec/exec_engine.c.i

exec/exec_engine.s: exec/exec_engine.c.s
.PHONY : exec/exec_engine.s

# target to generate assembly for a file
exec/exec_engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/exec_engine.c.s
.PHONY : exec/exec_engine.c.s

exec/runtime_storage.o: exec/runtime_storage.c.o
.PHONY : exec/runtime_storage.o

# target to build an object file
exec/runtime_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_storage.c.o
.PHONY : exec/runtime_storage.c.o

exec/runtime_storage.i: exec/runtime_storage.c.i
.PHONY : exec/runtime_storage.i

# target to preprocess a source file
exec/runtime_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_storage.c.i
.PHONY : exec/runtime_storage.c.i

exec/runtime_storage.s: exec/runtime_storage.c.s
.PHONY : exec/runtime_storage.s

# target to generate assembly for a file
exec/runtime_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_storage.c.s
.PHONY : exec/runtime_storage.c.s

exec/runtime_val.o: exec/runtime_val.c.o
.PHONY : exec/runtime_val.o

# target to build an object file
exec/runtime_val.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_val.c.o
.PHONY : exec/runtime_val.c.o

exec/runtime_val.i: exec/runtime_val.c.i
.PHONY : exec/runtime_val.i

# target to preprocess a source file
exec/runtime_val.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_val.c.i
.PHONY : exec/runtime_val.c.i

exec/runtime_val.s: exec/runtime_val.c.s
.PHONY : exec/runtime_val.s

# target to generate assembly for a file
exec/runtime_val.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/exec/runtime_val.c.s
.PHONY : exec/runtime_val.c.s

lang/ast_expr.o: lang/ast_expr.c.o
.PHONY : lang/ast_expr.o

# target to build an object file
lang/ast_expr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_expr.c.o
.PHONY : lang/ast_expr.c.o

lang/ast_expr.i: lang/ast_expr.c.i
.PHONY : lang/ast_expr.i

# target to preprocess a source file
lang/ast_expr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_expr.c.i
.PHONY : lang/ast_expr.c.i

lang/ast_expr.s: lang/ast_expr.c.s
.PHONY : lang/ast_expr.s

# target to generate assembly for a file
lang/ast_expr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_expr.c.s
.PHONY : lang/ast_expr.c.s

lang/ast_stmt.o: lang/ast_stmt.c.o
.PHONY : lang/ast_stmt.o

# target to build an object file
lang/ast_stmt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_stmt.c.o
.PHONY : lang/ast_stmt.c.o

lang/ast_stmt.i: lang/ast_stmt.c.i
.PHONY : lang/ast_stmt.i

# target to preprocess a source file
lang/ast_stmt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_stmt.c.i
.PHONY : lang/ast_stmt.c.i

lang/ast_stmt.s: lang/ast_stmt.c.s
.PHONY : lang/ast_stmt.s

# target to generate assembly for a file
lang/ast_stmt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_stmt.c.s
.PHONY : lang/ast_stmt.c.s

lang/ast_visit.o: lang/ast_visit.c.o
.PHONY : lang/ast_visit.o

# target to build an object file
lang/ast_visit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_visit.c.o
.PHONY : lang/ast_visit.c.o

lang/ast_visit.i: lang/ast_visit.c.i
.PHONY : lang/ast_visit.i

# target to preprocess a source file
lang/ast_visit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_visit.c.i
.PHONY : lang/ast_visit.c.i

lang/ast_visit.s: lang/ast_visit.c.s
.PHONY : lang/ast_visit.s

# target to generate assembly for a file
lang/ast_visit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/ast_visit.c.s
.PHONY : lang/ast_visit.c.s

lang/function.o: lang/function.c.o
.PHONY : lang/function.o

# target to build an object file
lang/function.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/function.c.o
.PHONY : lang/function.c.o

lang/function.i: lang/function.c.i
.PHONY : lang/function.i

# target to preprocess a source file
lang/function.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/function.c.i
.PHONY : lang/function.c.i

lang/function.s: lang/function.c.s
.PHONY : lang/function.s

# target to generate assembly for a file
lang/function.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/function.c.s
.PHONY : lang/function.c.s

lang/symbol.o: lang/symbol.c.o
.PHONY : lang/symbol.o

# target to build an object file
lang/symbol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/symbol.c.o
.PHONY : lang/symbol.c.o

lang/symbol.i: lang/symbol.c.i
.PHONY : lang/symbol.i

# target to preprocess a source file
lang/symbol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/symbol.c.i
.PHONY : lang/symbol.c.i

lang/symbol.s: lang/symbol.c.s
.PHONY : lang/symbol.s

# target to generate assembly for a file
lang/symbol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lang/symbol.c.s
.PHONY : lang/symbol.c.s

lib/diagnostics.o: lib/diagnostics.c.o
.PHONY : lib/diagnostics.o

# target to build an object file
lib/diagnostics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/diagnostics.c.o
.PHONY : lib/diagnostics.c.o

lib/diagnostics.i: lib/diagnostics.c.i
.PHONY : lib/diagnostics.i

# target to preprocess a source file
lib/diagnostics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/diagnostics.c.i
.PHONY : lib/diagnostics.c.i

lib/diagnostics.s: lib/diagnostics.c.s
.PHONY : lib/diagnostics.s

# target to generate assembly for a file
lib/diagnostics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/diagnostics.c.s
.PHONY : lib/diagnostics.c.s

lib/str.o: lib/str.c.o
.PHONY : lib/str.o

# target to build an object file
lib/str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/str.c.o
.PHONY : lib/str.c.o

lib/str.i: lib/str.c.i
.PHONY : lib/str.i

# target to preprocess a source file
lib/str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/str.c.i
.PHONY : lib/str.c.i

lib/str.s: lib/str.c.s
.PHONY : lib/str.s

# target to generate assembly for a file
lib/str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/str.c.s
.PHONY : lib/str.c.s

lib/util.o: lib/util.c.o
.PHONY : lib/util.o

# target to build an object file
lib/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/util.c.o
.PHONY : lib/util.c.o

lib/util.i: lib/util.c.i
.PHONY : lib/util.i

# target to preprocess a source file
lib/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/util.c.i
.PHONY : lib/util.c.i

lib/util.s: lib/util.c.s
.PHONY : lib/util.s

# target to generate assembly for a file
lib/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/util.c.s
.PHONY : lib/util.c.s

lib/vector.o: lib/vector.c.o
.PHONY : lib/vector.o

# target to build an object file
lib/vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/vector.c.o
.PHONY : lib/vector.c.o

lib/vector.i: lib/vector.c.i
.PHONY : lib/vector.i

# target to preprocess a source file
lib/vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/vector.c.i
.PHONY : lib/vector.c.i

lib/vector.s: lib/vector.c.s
.PHONY : lib/vector.s

# target to generate assembly for a file
lib/vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/lib/vector.c.s
.PHONY : lib/vector.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/main.c.s
.PHONY : main.c.s

parse/lexer.o: parse/lexer.c.o
.PHONY : parse/lexer.o

# target to build an object file
parse/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/lexer.c.o
.PHONY : parse/lexer.c.o

parse/lexer.i: parse/lexer.c.i
.PHONY : parse/lexer.i

# target to preprocess a source file
parse/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/lexer.c.i
.PHONY : parse/lexer.c.i

parse/lexer.s: parse/lexer.c.s
.PHONY : parse/lexer.s

# target to generate assembly for a file
parse/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/lexer.c.s
.PHONY : parse/lexer.c.s

parse/parser.o: parse/parser.c.o
.PHONY : parse/parser.o

# target to build an object file
parse/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/parser.c.o
.PHONY : parse/parser.c.o

parse/parser.i: parse/parser.c.i
.PHONY : parse/parser.i

# target to preprocess a source file
parse/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/parser.c.i
.PHONY : parse/parser.c.i

parse/parser.s: parse/parser.c.s
.PHONY : parse/parser.s

# target to generate assembly for a file
parse/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/parser.c.s
.PHONY : parse/parser.c.s

parse/token.o: parse/token.c.o
.PHONY : parse/token.o

# target to build an object file
parse/token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/token.c.o
.PHONY : parse/token.c.o

parse/token.i: parse/token.c.i
.PHONY : parse/token.i

# target to preprocess a source file
parse/token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/token.c.i
.PHONY : parse/token.c.i

parse/token.s: parse/token.c.s
.PHONY : parse/token.s

# target to generate assembly for a file
parse/token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClashC.dir/build.make CMakeFiles/ClashC.dir/parse/token.c.s
.PHONY : parse/token.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ClashC"
	@echo "... exec/exec_engine.o"
	@echo "... exec/exec_engine.i"
	@echo "... exec/exec_engine.s"
	@echo "... exec/runtime_storage.o"
	@echo "... exec/runtime_storage.i"
	@echo "... exec/runtime_storage.s"
	@echo "... exec/runtime_val.o"
	@echo "... exec/runtime_val.i"
	@echo "... exec/runtime_val.s"
	@echo "... lang/ast_expr.o"
	@echo "... lang/ast_expr.i"
	@echo "... lang/ast_expr.s"
	@echo "... lang/ast_stmt.o"
	@echo "... lang/ast_stmt.i"
	@echo "... lang/ast_stmt.s"
	@echo "... lang/ast_visit.o"
	@echo "... lang/ast_visit.i"
	@echo "... lang/ast_visit.s"
	@echo "... lang/function.o"
	@echo "... lang/function.i"
	@echo "... lang/function.s"
	@echo "... lang/symbol.o"
	@echo "... lang/symbol.i"
	@echo "... lang/symbol.s"
	@echo "... lib/diagnostics.o"
	@echo "... lib/diagnostics.i"
	@echo "... lib/diagnostics.s"
	@echo "... lib/str.o"
	@echo "... lib/str.i"
	@echo "... lib/str.s"
	@echo "... lib/util.o"
	@echo "... lib/util.i"
	@echo "... lib/util.s"
	@echo "... lib/vector.o"
	@echo "... lib/vector.i"
	@echo "... lib/vector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse/lexer.o"
	@echo "... parse/lexer.i"
	@echo "... parse/lexer.s"
	@echo "... parse/parser.o"
	@echo "... parse/parser.i"
	@echo "... parse/parser.s"
	@echo "... parse/token.o"
	@echo "... parse/token.i"
	@echo "... parse/token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

